[package]
name = "lc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lc"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
regex = "1"
tempfile = "3"
colored = "3"
